version: '3.7'
services:
#  flask:
#   build: .
#   container_name: e8_in_docker
#   image: tiangolo/uwsgi-nginx:python3.8
#   environment:
#    - PORT=5000
#    - DB_NAME=e8
##    - NSQ_HOST=nsqd
##    - NSQ_PORT=4151
#    - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/e8
#   command: bash -c "alembic upgrade head && gunicorn -w 4 -b 0.0.0.0:5000 api:app"
#   ports:
#     - "5000:5000"
#   depends_on:
#     - redis
#     - postgres
##     - nsqd
#     - worker
#   links:
#     - postgres
#     - worker
#     - redis
#   volumes:
#     - .:/app
#
#  worker:
#    build:
#      context: .
#      dockerfile: _celery/Dockerfile
#    user: nobody
#    environment:
#      - BROKER_HOST=redis://redis:6379/0
#      - NSQ_HOST=nsqd
#      - NSQ_PORT=4151
#    links:
#      - redis
#      - nsqd
#    depends_on:
#      - redis
#      - nsqd
#    volumes:
#        - .:/app

  nsqreader:
    build:
      context: .
      dockerfile: nsqreader/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/e8
      - NSQ_HOST=nsqd
      - NSQ_PORT=4150
    depends_on:
      - postgres
      - nsqd
    links:
      - postgres
      - nsqd

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

  redis:
    image: redis:latest
    container_name: redis-e8
    ports:
      - 6379:6379
    command: redis-server

  postgres:
    image: postgres:latest
    container_name: flask-db-e8
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=e8
    ports:
       - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    driver: local