version: '3.7'
services:
#  flask:
#   build: .
#   container_name: e9_in_docker
#   restart: always
#   image: tiangolo/uwsgi-nginx:python3.8
#   environment:
#    - PORT=5000
#    - DB_NAME=e9
#    - DATABASE_URL=postgresql://e9user:e9user@postgres:5432/e9
#   command: bash -c "alembic upgrade head && gunicorn -w 4 -b 0.0.0.0:5000 api:app"
#   ports:
#     - "5000:5000"
#   depends_on:
#     - redis
#     - postgres
#   links:
#     - postgres
#     - redis
#   volumes:
#     - .:/app


  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis-e9
    ports:
      - 6379:6379
    command: redis-server

  postgres:
    image: postgres:latest
    container_name: flask-db-e9
    restart: unless-stopped
    environment:
      - POSTGRES_USER=e9user
      - POSTGRES_PASSWORD=e9user
      - POSTGRES_DB=e9
    ports:
       - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    driver: local