"""initial migration

Revision ID: b4eaf2ba618c
Revises: 9810bab8a3a7
Create Date: 2020-10-24 05:08:29.734058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4eaf2ba618c'
down_revision = '9810bab8a3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
