"""initial migration

Revision ID: c17c64afddae
Revises: 
Create Date: 2020-10-21 15:58:14.553685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from api import bcrypt

revision = 'c17c64afddae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('event',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_begin', sa.DateTime(), nullable=True),
    sa.Column('timestamp_end', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(user_table,
                   [
                       {'_id': 1,
                        'email': 'admin@test.ru',
                        'name': 'admin',
                        'password': bcrypt.generate_password_hash('admin').decode('utf-8'),
                        }
                   ]
                   )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('user')
    # ### end Alembic commands ###
